name: 03 - Workflow Runners

on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the OS
              run: echo "Runner is running on a $RUNNER_OS operating system."
