name: 04 Using - Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: setup node 
              uses: actions/setup-node@v6
              with:
                node-version: '24.x'
                
            - name: Install Dependencies
              run: npm ci 
              working-directory: 04-using-actions/react-app  
              

        #checkout code
        #1install react dependencies
        # 2exe auotmated tests
