name: 04 Using - Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Printing folders
              run: ls -R

        #checkout code
        #1install react dependencies
        # 2exe auotmated tests
