name: 05 - 2 - Event filters and activity type

on:
    pull_request:
        types:
            - closed
        branches:
            - main    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Running when PR is closed "